language: ruby
rvm:
  - 2.4

before_script:
  - sed -i -e 's#baseurl: "/Ninja-Jekyll"#baseurl: "/"#' _config.yml

script:
  - bundle exec jekyll build
  - bundle exec htmlproofer ./_site
  - find ./_site

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

sudo: false
